import turtle
import time

    
def top_layer():
    turtle.clearscreen()
    screen_setup()
    stations()
    sp = turtle.Turtle()
    sp.color('white')
    sp.penup()
    sp.setpos(200, 75)
    sp.showturtle()
    sp.speed(1)      
    def sta1():
        sp.goto(200, 75)
    def sta2():
        sp.goto(-300, 45)
    def sta3():
        sp.goto(-100,-200)
    def zoom1():
        if sp.pos() == (200,75):
            middle_layer_sta1()
        else:
            zoom()
    turtle.onkey(sta1, 'a')
    turtle.onkey(sta2, 'b')
    turtle.onkey(sta3, 'c')
    turtle.onkey(zoom1, '=')
    turtle.listen()

def station_1():
    sta= turtle.Turtle()
    sta.color('white')
    sta.penup()
    sta.speed(0)
    sta.hideturtle()
    sta.setpos(-250,160)
    sta.pendown()
    sta.seth(0)
    #top two parts
    for i in range (2):
        sta.forward(30)
        sta.right(90)
        sta.forward(10)
        sta.right(90)
    sta.penup()
    sta.setpos(-255,150)
    sta.seth(0)
    sta.pendown()
    for i in range(2):
        sta.forward(40)
        sta.right(90)
        sta.forward(10)
        sta.right(90)
    sta.penup()
    sta.setpos(-253,140)
    sta.seth(0)
    sta.pendown()
    for i in range(2):
        sta.forward(36)
        sta.right(90)
        sta.forward(10)
        sta.right(90)
    #conector 1
    sta.penup()
    sta.setpos(-250,130)
    sta.seth(0)
    sta.pendown()
    for i in range(2):
        sta.forward(30)
        sta.right(90)
        sta.forward(10)
        sta.right(90)
    #ring 1
    sta.penup()
    sta.setpos(-310,120)
    sta.seth(0)
    sta.pendown()
    for i in range(2):
        sta.forward(150)
        sta.right(90)
        sta.forward(20)
        sta.right(90)
    #conector 2
    sta.penup()
    sta.setpos(-250,100)
    sta.seth(0)
    sta.pendown()
    for i in range(2):
        sta.forward(30)
        sta.right(90)
        sta.forward(15)
        sta.right(90)
    #ring 2
    sta.penup()
    sta.setpos(-310,85)
    sta.seth(0)
    sta.pendown()
    for i in range(2):
        sta.forward(150)
        sta.right(90)
        sta.forward(25)
        sta.right(90)
    #conector 3
    sta.penup()
    sta.setpos(-250,60)
    sta.seth(0)
    sta.pendown()
    for i in range(2):
        sta.forward(30)
        sta.right(90)
        sta.forward(15)
        sta.right(90)
    #ring 3
    sta.penup()
    sta.setpos(-310,45)
    sta.seth(0)
    sta.pendown()
    for i in range(2):
        sta.forward(150)
        sta.right(90)
        sta.forward(40)
        sta.right(90)
    #conector 4
    sta.penup()
    sta.setpos(-250,5)
    sta.seth(0)
    sta.pendown()
    for i in range(2):
        sta.forward(30)
        sta.right(90)
        sta.forward(15)
        sta.right(90)
    #ring 4
    sta.penup()
    sta.setpos(-310,-10)
    sta.seth(0)
    sta.pendown()
    for i in range(2):
        sta.forward(150)
        sta.right(90)
        sta.forward(20)
        sta.right(90)
    #conector 5
    sta.penup()
    sta.setpos(-250,-30)
    sta.seth(0)
    sta.pendown()
    for i in range(2):
        sta.forward(30)
        sta.right(90)
        sta.forward(15)
        sta.right(90)
    #junction 1
    sta.penup()
    sta.setpos(-260,-45)
    sta.seth(0)
    sta.pendown()
    for i in range(2):
        sta.forward(50)
        sta.right(90)
        sta.forward(20)
        sta.right(90)
    #arm 1
    sta.penup()
    sta.setpos(-260,-46)
    sta.setheading(270)
    sta.pendown()
    for i in range(2):
        sta.forward(18)
        sta.right(90)
        sta.forward(5)
        sta.right(90)
    sta.penup()
    sta.setpos(-265,-47)
    sta.seth(180)
    sta.pendown()
    for i in range(2):
        sta.forward(50)
        sta.left(90)
        sta.forward(16)
        sta.left(90)
    #motor 1 
    sta.penup()
    sta.setpos(-315,-41)
    sta.seth(270)
    sta.pendown()
    for i in range(2):
        sta.forward(28)
        sta.right(90)
        sta.forward(7)
        sta.right(90)
    sta.penup()
    sta.setpos(-322,-37)
    sta.seth(270)
    sta.pendown()
    for i in range(2):
        sta.forward(36)
        sta.right(90)
        sta.forward(9)
        sta.right(90)
    #ring 5
    sta.penup()
    sta.setpos(-331,-7)
    sta.pendown()
    sta.seth(270)
    for i in range(2):
        sta.forward(96)
        sta.right(90)
        sta.forward(15)
        sta.right(90)
    #arm 2
    sta.penup()
    sta.setpos(-210,-46)
    sta.seth(0)
    sta.pendown()
    for i in range(2):
        sta.forward(5)
        sta.right(90)
        sta.forward(18)
        sta.right(90)
    sta.penup()
    sta.setpos(-205,-47)
    sta.seth(0)
    sta.pendown()
    for i in range(2):
        sta.forward(30)
        sta.right(90)
        sta.forward(16)
        sta.right(90)
    #juntion 2 
    sta.penup()
    sta.setpos(-175,-46)
    sta.seth(0)
    sta.pendown()
    for i in range(4):
        sta.forward(18)
        sta.right(90)
    #arm 3
    sta.penup()
    sta.setpos(-162,-64)
    sta.seth(270)
    sta.pendown()
    for i in range(2):
        sta.forward(50)
        sta.right(90)
        sta.forward(10)
        sta.right(90)
    #docking bay
    sta.penup()
    sta.setpos(-162,-75)
    sta.seth(0)
    sta.pendown()
    for i in range(5):
        sta.forward(10)
        sta.right(90)
        sta.forward(2)
        sta.right(90)
        sta.forward(10)
        sta.left(90)
        sta.forward(5)
        sta.left(90)
    #solar panels
        #strut 1
    sta.penup()
    sta.setpos(-250,-65)
    sta.seth(270)
    sta.pendown()
    for i in range(1):
        sta.forward(70)
        sta.right(90)
        sta.forward(70)
        sta.right(90)
        sta.forward(2)
        sta.right(90)
        sta.forward(68)
        sta.left(90)
        sta.forward(68)
        #strut 2
    sta.penup()
    sta.setpos(-220,-65)
    sta.seth(270)
    sta.pendown()
    for i in range(1):
        sta.forward(70)
        sta.left(90)
        sta.forward(70)
        sta.left(90)
        sta.forward(2)
        sta.left(90)
        sta.forward(68)
        sta.right(90)
        sta.forward(68)
    sta.penup()
    sta.setpos(-250,-70)
    sta.seth(0)
    sta.pendown()
    for i in range(14):
        sta.forward(14)
        sta.right(90)
        sta.forward(4)
        sta.right(90)
        sta.forward(14)
        sta.left(180)
    sta.penup()
    sta.setpos(-252,-70)
    sta.seth(180)
    sta.pendown()
    for i in range(14):
        sta.forward(18)
        sta.left(90)
        sta.forward(4)
        sta.left(90)
        sta.forward(18)
        sta.right(180)
    sta.penup()
    sta.setpos(-272,-133)
    sta.seth(90)
    sta.pendown()
    for i in range(11):
        sta.forward(18)
        sta.left(90)
        sta.forward(4)
        sta.left(90)
        sta.forward(18)
        sta.right(180)
    sta.penup()
    sta.setpos(-220,-70)
    sta.seth(180)
    sta.pendown()
    for i in range(14):
        sta.forward(14)
        sta.left(90)
        sta.forward(4)
        sta.left(90)
        sta.forward(14)
        sta.right(180)
    sta.penup()
    sta.setpos(-218,-70)
    sta.seth(0)
    sta.pendown()
    for i in range(14):
        sta.forward(18)
        sta.right(90)
        sta.forward(4)
        sta.right(90)
        sta.forward(18)
        sta.left(180)
    sta.penup()
    sta.setpos(-198,-133)
    sta.seth(90)
    sta.pendown()
    for i in range(11):
        sta.forward(18)
        sta.right(90)
        sta.forward(4)
        sta.right(90)
        sta.forward(18)
        sta.right(180)
    sta.penup()
    sta.setpos(-154,-135)
    sta.seth(270)
    sta.pendown()
    for i in range(14):
        sta.forward(18)
        sta.right(90)
        sta.forward(4)
        sta.right(90)
        sta.forward(18)
        sta.right(180)
    sta.penup()
    sta.setpos(-260,-135)
    sta.seth(270)
    sta.pendown()
    for i in range(14):
        sta.forward(18)
        sta.right(90)
        sta.forward(4)
        sta.right(90)
        sta.forward(18)
        sta.right(180)
    skm = turtle.Turtle()
    skm.hideturtle()
    skm.color('white')
    skm.speed(0)
    skm.penup()
    skm.setpos(-162,-64)
    skm.seth(0)
    for i in range(8):
        skm.forward(5)
        skm.pendown()
        skm.forward(3)
        skm.penup()
    skm.right(90)
    for i in range(6):
        skm.forward(5)
        skm.pendown()
        skm.forward(3)
        skm.penup()
    skm.right(90)
    for i in range(8):
        skm.forward(5)
        skm.pendown()
        skm.forward(3)
        skm.penup()
    skm.setpos(-162,-77)
    skm.write('Docking Port', font=('Arial', 7, 'normal'))

    
    
def stations():
    station = turtle.Turtle()
    station.color('white')
    station.penup()
    station.shape('circle')
    station.speed(0)
    station.resizemode('user')
    station.shapesize(0.3, 0.3, 0.3)
    station.setpos(200, 75)
    station.stamp()
    station.write('station 001')
    station.setpos(-300, 45)
    station.stamp()
    station.write('station 002')
    station.setpos(-100,-200)
    station.stamp()
    station.write('station 003')


def screen_setup():
    turtle.setup(900, 500, 0,0)
    turtle.title("Navigation system")
    turtle.bgcolor('black')
    con = turtle.Turtle()
    con.penup()
    con.speed(0)
    con.color('white')
    con.hideturtle()
    con.setpos(420, -230)
    con.write('+')
    con.setpos(430, -230)
    con.write('-')

def docking_port1():
    #MAIN BODY
    dp1 = turtle.Turtle()
    dp1.hideturtle()
    dp1.color('white')
    dp1.speed(0)
    dp1.penup()
    dp1.setpos(-400,-250)
    dp1.pendown()
    dp1.seth(90)
    for i in range(5):
        dp1.forward(35)
        dp1.right(90)
        dp1.forward(200)
        dp1.left(90)
        dp1.forward(30)
        dp1.left(90)
        dp1.forward(200)
        dp1.right(90)
        dp1.forward(35)
    #AIR LOCKS
    dp1.penup()
    dp1.setpos(-370,-215)        
    for i in range(5):
        dp1.seth(270)
        dp1.pendown()
        for i in range(4):
            dp1.forward(3)
            dp1.left(90)
            dp1.forward(8)
            dp1.left(90)
            dp1.forward(3)
            dp1.right(90)
            dp1.forward(30)
            dp1.right(90)
        dp1.penup()
        dp1.seth(90)
        dp1.forward(30)
        dp1.seth(180)
        dp1.forward(152)
        dp1.seth(90)
        dp1.pendown()
        for i in range(4):
            dp1.forward(3)
            dp1.right(90)
            dp1.forward(8)
            dp1.right(90)
            dp1.forward(3)
            dp1.left(90)
            dp1.forward(30)
            dp1.left(90)
        dp1.penup()
        dp1.seth(90)
        dp1.forward(70)
        dp1.seth(180)
        dp1.forward(152)
    #PANELS 1
    dp1.penup()
    dp1.setpos(-255,-215)
    for i in range(5):
        dp1.seth(90)
        dp1.pendown()
        dp1.forward(30)
        dp1.left(90)
        dp1.forward(40)
        dp1.left(90)
        dp1.forward(30)
        dp1.seth(90)
        dp1.forward(15)
        dp1.left(90)
        dp1.forward(20)
        dp1.right(90)
        dp1.forward(15)
        dp1.right(180)
        dp1.forward(30)
        dp1.right(90)
        dp1.forward(30)
        dp1.right(90)
        dp1.forward(30)
        dp1.seth(270)
        for i in range(2):
            dp1.forward(10)
            dp1.right(90)
            dp1.forward(40)
            dp1.left(180)
            dp1.forward(40)
            dp1.right(90)
        dp1.forward(10)
        dp1.right(90)
        dp1.forward(40)
        dp1.right(90)
        dp1.forward(30)
        dp1.left(90)
        dp1.forward(15)
        dp1.left(90)
        dp1.forward(30)
        dp1.penup()
        dp1.seth(90)
        dp1.forward(100)
        dp1.setx(-255)
    #PANELS 2
    dp1.penup()
    dp1.setpos(-400,-220)
    dp1.pendown()
    for i in range(4):
        dp1.seth(180)
        dp1.forward(50)
        dp1.seth(0)
        dp1.forward(25)
        dp1.left(90)
        dp1.forward(40)
        dp1.left(90)
        dp1.forward(25)
        dp1.seth(0)
        for i in range(2):
            dp1.forward(16.6)
            dp1.left(90)
            dp1.forward(50)
            dp1.seth(270)
            dp1.forward(50)
            dp1.seth(0)
        dp1.setx(-400)
        for i in range(2):
            dp1.left(90)
            dp1.forward(50)
        dp1.seth(0)
        dp1.forward(50)
        dp1.left(90)
        dp1.forward(30)
    
        
         
    
def docking_layer():
    turtle.clearscreen()
    screen_setup()
    docking_port1()
    sp3 = turtle.Turtle()
    sp3.color('white')
    sp3.penup()
    sp3.speed(0)
    sp3.setpos(300, 0)
    sp3.seth(180)
    sp3.showturtle()
    speed = (10)
    def turnleft():
        sp3.left(30)
    def turnright():
        sp3.right(30)
    def forward():
        sp3.forward(speed)
    def backward():
        sp3.backward(speed)
        
    turtle.onkey(forward, 'Up')
    turtle.onkey(turnleft, 'Left')
    turtle.onkey(turnright, 'Right')
    turtle.onkey(backward, 'Down')
    turtle.onkey(middle_layer_sta1, '-')
    turtle.listen()
    

def middle_layer_sta1():
    time.sleep(0.5)
    turtle.clearscreen()
    screen_setup()
    station_1()
    sp2 = turtle.Turtle()
    sp2.color('white')
    sp2.penup()
    sp2.speed(0)
    sp2.setpos(250, -150)
    sp2.seth(90)
    sp2.showturtle()
    speed = (10)
    b = 2
    def turnleft():
        sp2.left(30)
    def turnright():
        sp2.right(30)
    def forward():
        sp2.forward(speed)
    def backward():
        sp2.backward(speed)
    def zoom1():
        if sp2.xcor() > -162 and sp2.xcor() < -98 and sp2.ycor() > -112 and sp2.ycor() < -64:
            docking_layer()
    
            
    turtle.onkey(forward, 'Up')
    turtle.onkey(turnleft, 'Left')
    turtle.onkey(turnright, 'Right')
    turtle.onkey(backward, 'Down')
    turtle.onkey(top_layer, '-')
    turtle.onkey(zoom1,'=')
    turtle.listen()
      
def zoom():
    time.sleep(0.5)
    turtle.clearscreen()
    screen_setup()
    sp2 = turtle.Turtle()
    sp2.color('white')
    sp2.penup()
    sp2.speed(0)
    sp2.setpos(250, -150)
    sp2.seth(90)
    sp2.showturtle()
    speed = (10)
    b = 2
    def turnleft():
        sp2.left(30)
    def turnright():
        sp2.right(30)
    def forward():
        sp2.forward(speed)
    def backward():
        sp2.backward(speed)    
    
            
    turtle.onkey(forward, 'Up')
    turtle.onkey(turnleft, 'Left')
    turtle.onkey(turnright, 'Right')
    turtle.onkey(backward, 'Down')
    turtle.onkey(top_layer, '-')
    turtle.listen()


top_layer()
